### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by pacomms** [pot0rpan/screeps#2]
Wheni do rollup -c i get the folowing error

src/main.ts → dist/main.js...
[!] (plugin rpt2) Error: /npm/screeps-main/src/utils/Traveler.ts(645,37): semantic error TS2344: Type 'Structure<StructureConstant>' does not satisfy the constraint 'AnyStructure'.
  Property 'ticksToLive' is missing in type 'Structure<StructureConstant>' but required in type 'StructureWall'.
src/utils/Traveler.ts
Error: /npm/screeps-main/src/utils/Traveler.ts(645,37): semantic error TS2344: Type 'Structure<StructureConstant>' does not satisfy the constraint 'AnyStructure'.
  Property 'ticksToLive' is missing in type 'Structure<StructureConstant>' but required in type 'StructureWall'.
    at error (/usr/local/lib/node_modules/rollup/dist/shared/rollup.js:151:30)
    at throwPluginError (/usr/local/lib/node_modules/rollup/dist/shared/rollup.js:19344:12)
    at Object.error (/usr/local/lib/node_modules/rollup/dist/shared/rollup.js:20013:20)
    at Object.error (/usr/local/lib/node_modules/rollup/dist/shared/rollup.js:19520:38)
    at RollupContext.error (/npm/screeps-main/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:17237:30)
    at /npm/screeps-main/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:25033:23
    at arrayEach (/npm/screeps-main/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:545:11)
    at Function.forEach (/npm/screeps-main/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:9397:14)
    at printDiagnostics (/npm/screeps-main/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:25006:12)
    at Object.transform (/npm/screeps-main/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:29277:17)

any ideas ?

**Comment by pot0rpan** [comment]
Hmm, I'm not sure but I'll take a look.  I've never had issues with Traveler types.

**Comment by pacomms** [comment]
thanks alot :-) great response as well

**Comment by pot0rpan** [comment]
@pacomms this is difficult to debug since I'm not getting the error, but try now. I added this change: 43e9f19e225fb6364485e3f5f8f53a505474e820

**Comment by pacomms** [comment]
yep thats compiled now, do you have any docs on this code like flag colors wot they do etc ? im pretty new to all this but love screeps just need a start with the code :-)

**Comment by pacomms** [comment]
Sorry just a question , should this code just run as is as a starter, i have deployed it but nothing spawns i just get tick number and empire in the console ?

**Comment by pot0rpan** [comment]
Awesome, wasn't sure what else to try if it didn't work.

No docs yet really, since I'm still changing things fairly often.  For flags, look at config.ts to find flag colors.  Right now there's only 1 there, for expanding to create new colonies.  I've been planning on moving the other flag colors there as well (other flags are only for attacking currently), so I'll do that next so you can see all the flag types in one spot.  

But if you're just starting, no flags are needed for that.  The important part is to place your spawn in the correct spot where the bunker will fit.  Look at my rooms on shard2 to see an example of where the first spawn goes in relation to the bunker layout, or check out [the building plan](https://screeps.admon.dev/building-planner/?share=N4IgdghgtgpiBcIQBoQHcD2AnANgEwRCigxRAGcALCLAxKmvABjKwGMcEAOVAIwFcAlvkFgA5uQShyABwhowUkDIyT4AbVAAPBACYArKgCeegIwBfZNr0AWYwlNdL1+Lp4gTriwF1LFAC7YEGJw8KAqapogOq6GHnq65r6oOKIA1koRCFExugDM9q55SX6BaDBYmarZLrp28UXO0baFuhZWza66rYkduQBsPU259Z66TMMtDXUlqP4VUKIQnGHK1Rq1BdOJySBYGBB04es5U56mAJyTRa0TfQmt7bWmQ-ddrcVv+a0213Wt+j+cTGvy+g2mn1qAHZXrVwWMnp0DLc-lsxv0-kxHtdLiivsCHE4wYVTFC-u4xpCkRcfn9Rg4MfiSYy4cy6a0ibVutNOUi0XpebkCa5BXp4QLUWyvtzzizOo5YfKKWYccrXHcXAqIaraW88ljphrOvrsXqDWNei4Tdqzbqua0yV8adNAV81bo5bkYdNHZrnWNXbVzWK-i8faGSb6kcH4I4cf6HFcnSSk7U1XGvt7zmTdjAtPMwORBBhFKsshs+QC-jLbBGbUHFTFcdNEU2E11MR86yDq1Xpa1PWY+w3pqC-V2vmGEb3DZKGpdyY29Fm9FSBnakcKDOzpoObuG3s2e18Y9vJwPO7OTynu4nb+qZ+dU0ia7HRV4Se-dK-STvs3Pzi-flYyjIVIz-ZcgQdP5xVcUCxQvJldxg4ckRXWI-nQj1FxdHDj2hDdcnbfI-mIy1qVNWpiImXYcAgXgqkiWphQXYl5y-WDWII9jMJvNixiNL08TTPjuOnN0UV2MB+DSCpGJqTcu12DBeHICoADc5LLE5NmxXxzHMIA) for the full picture (note the most center spawn must be placed first).

**Comment by pot0rpan** [comment]
> Sorry just a question , should this code just run as is as a starter, i have deployed it but nothing spawns i just get tick number and empire in the console ?

This is probably because right now the username is hardcoded, I haven't yet moved it to an easily editable environment variable.  So edit config.js to change `USERNAME` to your in-game name.  And less important, you can edit `FRIENDLY_NAMES` to specify who _not_ to attack.

**Comment by pacomms** [comment]
cool thanks alot :-) i will watch this git as i like the code style, will look into adding more flags as i dont want everything automated, does this autobuild structures etc ?

**Comment by pot0rpan** [comment]
No problem!  If you don't mind me asking, how'd you find this repo?  I figured it would get buried under all the other "screeps" repos and no one would ever find it.

And yes, it autobuilds all necessary structures in the main colony room only.  It also auto expands to start remote mining at rcl 4.  One other thing to be aware of, if sources/controller are too close, things break a bit.  So try not to get a room like [this](https://screeps.com/a/#!/room/shard2/E39S52) or you'll end up having to manually fix some stuff the room planner does.

**Comment by pacomms** [comment]
I was just scrolling through the github codes looking for ideas, i like the idea of using flags to control my screeps, i will look at implementing attack and defend flags ... well once i figure it all out lol

**Comment by pacomms** [comment]
sorry just noticed, do you have a flag for attacking already ?

**Comment by pot0rpan** [comment]
Defense is handled automatically, for both main colony room and remote harvesting rooms.  And yes attacking is all flag-based.  I'm about to move the attack flag colors to config.flags so it's easier to find.  But for now, if you place a red/green flag in any room within 5 rooms of the main colony room, it'll spawn an attacker and healer pair, then go to the flag room and attack.

**Comment by pacomms** [comment]
awesome will look at that :-) i hope you dont mind me asking questions its kinda easier than trawling through the initial code :-)

**Comment by pot0rpan** [comment]
No not at all, ask away!

Just moved all flag colors to config.ts, also added small comments to explain what they do.

**Comment by pacomms** [comment]
Awesome will take a look now, is teh ammount of attackers configurable, ie send 2 melee instead of 1 or does it go by RCL and energy ?

**Comment by pot0rpan** [comment]
That just goes by number of flags, so you have to make the decision of if it's worth it and will be strong enough  at the current RCL.  Each pair gets assigned a flag, so if you put 2 flags in a room it should spawn 2 pairs, 1 for each flag.

**Comment by pacomms** [comment]
ahh perfect :-) awesome , is there a factory support and powerscreep support ?

**Comment by pot0rpan** [comment]
Attackers/healers also spawn before most other creeps, so be careful not to leave a flag too long if your attackers keep getting killed, or it could start starving the colony.

No factory or power stuff yet, or boosts.  Labs/boosts are my next big to-do item, but it'll probably be a while as I need to figure out a good way to handle it.

**Comment by pacomms** [comment]
cool, well will watch you stuff with interest :- ) if i figure anything good i will of course share with you, thanks for putting your code up it really helps newbies ..

**Comment by pot0rpan** [comment]
No problem, thanks for checking it out!  Any advice or suggestions are welcome.

So I'm assuming changing USERNAME fixed it for you and stuff started spawning then?

**Comment by pacomms** [comment]
yes it seems to have, i have it on a private server for now with just a few bots has spawned stuff and seems to be upgrading etc so far, will see about the layout etc, does it spawn walls and ramparts and roads ? is there any way to increase the display on the room to include more info etc .. debug console

**Comment by pot0rpan** [comment]
Ok nice.  It makes ramparts around the bunker and controller, and roads to sources, controller, and at rcl 6 mineral.  Also places containers/links.  If you look at any of my rooms on shard2, everything that has been build was built automatically (except containers in remote mining rooms, that's manual for now).

The room visuals aren't configurable yet, all you can do is turn them on and off by typing `stats.show = true/false` in the console.  All the blue profiling logs can be turned on and off in a similar way, `stats.profile = true/false`.  If you want to filter the profiling results you can do it with `stats.filter()`.  Most profiling logs are given "categories", like the room name, creep name, and creep role (if applicable).  So to only show profiling for Pioneer creeps in room E1S1 you would do `stats.filter('E1S1', 'pioneer')`.  But on a global reset or code push the profiling filter gets removed, that's not saved in memory currently.  To turn _off_ the filtering, just do an empty `stats.filter()`.

Hope that helps, I'll get around to documenting those "hidden" things at some point.

**Comment by pacomms** [comment]
Hey bud, quick question my room only seems to be spawning builders and not dedicated miners and haulers i am at rcl 3 or do i need to place containers or something for the miners to spawn ?

Thanks :-)

**Comment by pot0rpan** [comment]
Builders should start to build roads and containers at RCL 3, then the harvesters should start spawning.

-------- Original Message --------

**Comment by pacomms** [comment]
kewl its just started doing just that :-) awesome

**Comment by pacomms** [comment]
sorry me again :-) when should remote miners start spawning ? do i need to place containers in other room to start mining them or a flag maybe ?

**Comment by pot0rpan** [comment]
I believe they start at RCL 4 once storage gets built, so the excess energy can be stored somewhere. They'll start spawning regardless of if containers exist, and container placement is manual atm.

Once they start spawning, place a container construction site under (or near) them and they'll build it then start using it.  Sometime soon I'll automate that so they place the construction site themselves.

**Comment by pacomms** [comment]
Ok thanks, i have placed a claim flag and its spawned a claimer and sent it to the room, however when the colonizers spawn it gets stuck as the colonizer doesnt move from in front of spawn, do claiming not occur until these guys get to the claim room ? is there a way to make them go sit at a white flag for example when idle so they dont block the spawn ?

**Comment by pot0rpan** [comment]
Hmm they should go to the claim room instead of sitting there, maybe they're waiting until the claimer claims it first?  I'll look into it later.  Let me know if they head to the new room once the Claimer claims it.

>is there a way to make them go sit at a white flag for example when idle so they dont block the spawn

Unfortunately, no.  Whenever creeps are `say`ing a countdown like "... 99" they should move out of the way of other stuck creeps (see https://github.com/pot0rpan/screeps/blob/main/src/actions/recycle.ts), but that doesn't check for a blocked spawn atm.  It also doesn't look like Colonizers are using that all the time, so they may end up blocking both creeps and spawning.  I'll work on fixing that.

**Comment by pacomms** [comment]
:-)

**Comment by pacomms** [comment]
ok so 3 colonizers have moved to the claim room, i have to kill a few to clear the spawn but now they sit there saying cmon ?

**Comment by pacomms** [comment]
hmm the claimer doesn't seem to have actually claimed the controller thats why the colonizers are doing nothing i guess, must be an issue with claimer maybe

**Comment by pot0rpan** [comment]
They say "cmon" if they got to the room and Claimer still hasn't claimed it.  What's the claimer doing?

**Comment by pacomms** [comment]
claimer just died and a new one isnt spawning, claimer just sat by the controller

**Comment by pacomms** [comment]
is there a command to manually spawn another claimer ?

**Comment by pacomms** [comment]
claimer just spawned lets see what this one does

**Comment by pacomms** [comment]
nah claimers just sitting there doing nothing

**Comment by pot0rpan** [comment]
It's adjacent to the controller?

**Comment by pacomms** [comment]
yes

**Comment by pacomms** [comment]
![screenshot](https://user-images.githubusercontent.com/38086033/132730448-97abeae7-1f53-4e14-a9d8-9662796fd080.png)

screenshot attached

**Comment by pot0rpan** [comment]
I won't be able to make any changes for a few hours, but maybe try putting some `console.log`s in this area to see what it's _trying_ to do.  That may help me debug for now until I can actually test it.
https://github.com/pot0rpan/screeps/blob/11c881b278ff37336dab66e04e60a8cec312716b/src/creeps/ClaimerCreep.ts#L92-L110

**Comment by pacomms** [comment]
wait a minute, can i even claim 2 rooms at gcl 1 ? maybe thats the issue

**Comment by pot0rpan** [comment]
OH! that's probably the issue then 😄 
Since colonizing is done manually with flags I never added a check for that.

**Comment by pacomms** [comment]
lol , ok rest easy then i need to raise my GCL then 1st

**Comment by pot0rpan** [comment]
You may be able to do that through the cli, I've never tried on my private server though.  May need a mod for it.

**Comment by pacomms** [comment]
okies

**Comment by pacomms** [comment]
Hey m8, only me again :-) , i have just sent some attack creeps to another bots room and they dont attack anything when they get there, i noticed this as well if i spawn an attack creep in main room and the spawn in an invader they dont attack the invader nor any other creeps, i have looked through attacker code but cant spot why they are not doing anything ?

**Comment by pot0rpan** [comment]
Hey,

The attackers should attack once they get to the room with the flag, but I'm not sure what happens if you put the flag in their home room.  When the home room has invaders or other hostiles, defenders should spawn unless the towers take them out first.

But if the attackers are in the flag room, and the flag room isn't their home room, then I'm not sure why they wouldn't be attacking.

**Comment by pacomms** [comment]
wierd , if i spawn invaders in the home room the defenders spawn but dont attack the invaders, same if i put attack flag in another room the attackers do spawn but do nothing when they get there

**Comment by pot0rpan** [comment]
> Ok thanks, i have placed a claim flag and its spawned a claimer and sent it to the room, however when the colonizers spawn it gets stuck as the colonizer doesnt move from in front of spawn

Also, this should be fixed now. They weren't heading to the room until the claimer claimed it and died due to a small copy/paste bug.

**Comment by pot0rpan** [comment]
> wierd , if i spawn invaders in the home room the defenders spawn but dont attack the invaders

Do you have ramparts in your home room? If so, defenders try to stay on ramparts and let the hostiles come to them.

**Comment by pacomms** [comment]
cool, yeah i spotted that fix :-) , yes i do have ramparts but even if i spawn invader next to it near enough they dont attack the invader, almost like the creep itself doesnt recognise hostiles, but the room must or it wouldnt spawn them. 

with the attackers again its wierd cos they do travel to the attack flag but dont do squat :-)

**Comment by pot0rpan** [comment]
Weird, I'll look into it.

**Comment by pacomms** [comment]
awesome :-)

**Comment by pot0rpan** [comment]
@pacomms it seems to work fine at least on MMO against players. https://screeps.com/a/#!/history/shard2/E44S48?t=35684037

Maybe it's an issue with invaders, but it shouldn't be.  Was the invader near the edge of the room? They ignore creeps within 4 squares of the edge for a lazy way of not bounding at an exit.

**Comment by pacomms** [comment]
hmm strange, i just tried again and it gets to room and says nope ? does that help

**Comment by pot0rpan** [comment]
When the healer can't keep up they retreat and say nope. But after getting healed they should try to attack again.

**Comment by pacomms** [comment]
Hmm well I been through it and it defo doesnt attack when I send troops to other rooms , it odd indeed but I can't see why , no errors I  an see and compiles ok, even removed the entries for friends but no go they just goto room and sit there . I wo der if its cos they are bots and ai ?

**Comment by dczysz** [comment]
Could be, but they search for hostile creeps, which picks up invaders for sure. I figured it would pick up other bots as well.

**Comment by pot0rpan** [comment]
Does `Game.rooms['roomname'].findHostiles().length` return > 0 in the room with the bot?

**Comment by pacomms** [comment]
gives this 

TypeError: Cannot read property 'findHostiles' of undefined
    at eval (eval at <anonymous> (_console1631475396628_0:1:46), <anonymous>:1:20)
    at _console1631475396628_0:1:46
    at _console1631475396628_0:1:60
    at Object.exports.evalCode (<runtime>:15336:71)
    at Object.exports.run (<runtime>:20819:41)

**Comment by pacomms** [comment]
i entered this 

Game.rooms['W3N8'].findHostiles().length

gives the above error

**Comment by pot0rpan** [comment]
Need visibility of the room first, like with an attacker creep there.

**Comment by pacomms** [comment]
ok lemme try again :-) i will send another attacker

**Comment by pacomms** [comment]
how would i stop the don't attack within 4 blocks , just wondering if that's a problem ?

**Comment by pot0rpan** [comment]
It's the `!hostile.pos.isNearEdge(5)` line in each of these.  Just comment out it and the `&&` before it.

https://github.com/pot0rpan/screeps/blob/77ecf349cf6e571b68bc138615948615697c11c0/src/creeps/AttackerCreep.ts#L175-L195

**Comment by pot0rpan** [comment]
```js
target = creep.pos.findClosestByPath(FIND_HOSTILE_CREEPS, {
  filter: hostile =>
    hostile.isHostile() &&
    hostile.isDangerous() // &&
    // !hostile.pos.isNearEdge(5),
});

// Potentially dangerous creep
if (!target) {
  target = creep.pos.findClosestByPath(FIND_HOSTILE_CREEPS, {
    filter: hostile => hostile.isHostile() // && !hostile.pos.isNearEdge(5),
  });
}

// Civilians
if (!target) {
  target = creep.pos.findClosestByPath(FIND_HOSTILE_CREEPS, {
    filter: crp =>
      !isFriendlyOwner(crp.owner.username) // && !crp.pos.isNearEdge(5),
  });
}
```

**Comment by pacomms** [comment]
Hmm, ok I'm wondering if the bot is activating safe mode then, maybe that's it ..

**Comment by pot0rpan** [comment]
Oh good point, just added a check so they should remove the flag and retreat if the flag room activates safemode.

**Comment by pacomms** [comment]
Good idea, i have added in creep.say('safe mode'); , so i can see if that's the issue. Interestingly i sent some attackers to a npc source room and they did try and attack, granted got their ass kicked but the tried bless em lol

**Comment by pacomms** [comment]
Hey m8, not sure if you are aware the attack seems to have been borked in the last few builds, i have told them to attack a room and they are not spawning any attacker creeps ?

**Comment by pot0rpan** [comment]
And you're using a red/red or red/green flag within 5 rooms of your colony, but not in the colony room itself, right? That should be the criteria for spawning attackers. I've attacked a few times over the last couple weeks and it worked fine for me. Not sure what the issue may be without more info.

-------- Original Message --------

**Comment by pacomms** [comment]
Yep, they are defo not spawning i put a red red in a room thats 3 away from my nearest colony and nothings spawning attack wise.. weird it was working ? hmm

**Comment by pot0rpan** [comment]
Hmm not sure then. I'll have to do some testing.

-------- Original Message --------

**Comment by pot0rpan** [comment]
Works fine on MMO for me.  Is your colony at least RCL 4?  It won't spawn any if lower since they're too weak to do much anyway.
